### PR TITLE
Major July update

### PR DESCRIPTION
**Pull request by nicbarajas**
- Add Sweet Chick, Mei Chi, Broccolino, Bar Meridian, Piquant
- Lots of other updates across the neighborhood, largely around outdoor seating.

### CODE REVIEW

**Comment by irace** [comment]
🙌

**Comment by nicbarajas** [comment]
Gonna do one more sanity check before merging and compare against today’s email!

**Comment by nicbarajas** [comment]
@irace could you review / merge? I think I’m good here but would like another pair of eyes for such a big change 😅

**Comment by irace** [comment]
Busy week and not sure when I’ll have time to review so I’m going to take a leap of faith and merge! 🤞

**Review by irace — APPROVED** [review]

**Review by irace — APPROVED** [review]

**Comment by nicbarajas** [comment]
Thanks - I’ll merge once I fix the conflicts.

**Pull request merged**
