### PR TITLE
Categories, services and social

### LINKED ISSUE #23: Venue categories
Idea: we should add categories so people can narrow down or we can reorganize the home page. Would help with #4 as nearly all businesses are priming to open back up.

### PR DESCRIPTION
**Pull request by nicbarajas**
Adds categories to listings and reorganizes the main page by category. This fixes #23 and paves the way to do work on #4. All places should have a category now, and I’ve put a `categories.yml` data file to generate the sections. This can lead to some discrepancy between entered categories and the official list, but the directory (see below) should help with that.

There’s additionally a new directory on the home page that includes all open and temporarily closed 🤞 places. (Taro is still in the `places.yml` file but now marked as permanently closed `:sadface:`.) Maybe it shouldn’t be a full directory? Let’s discuss.

Also includes a few other fixes:
- Renamed `delivery` to `services`, which will hopefully make it a little more extensible.
- Resy is added as an option in addition with its icon.
- Nested Instagram, Facebook and Untappd under a new `social` heading
- Re-sorted places alphabetically, but with name on top (thanks [yml-sorter](https://github.com/42BV/yml-sorter))

### CODE REVIEW

**Comment by nicbarajas** [comment]
One specific note about `places.yml` – since I generated it from the previous version, it’s got some funky formatting. I can go back through and clean that up if we like, though right now it’s not adversely affecting anything.

**Comment by nicbarajas** [comment]
@irace curious what you think here – I’ve got the old places file locally so I can revert if we just want the category changes.

**Comment by irace** [comment]
It feels _slightly_ odd to use equality checks on human readable strings to check category inclusion. I may be splitting hairs here but I wonder if it's slightly cleaner for a category object to look more like:

```yaml
id: wine-and-liquor-store
section_header: Wine & Liquor Stores
```

You’re still doing string matching in this case, but it seems a little better semantically as one is clearly an identifier that isn’t UI-facing, and the other is.

Other than that, it looks great! I‘d love to see a screenshot since it’s a little hard for me to wrap my head completely around the change just from looking at the delta, but no concerns on my end. Awesome work!

**Comment by nicbarajas** [comment]
Ah good call on using IDs! I’ll update the logic and get you a look at the new page.

**Comment by nicbarajas** [comment]
categories-desktop

~Here’s a [PDF of the page](https://github.com/irace/prospectheightsbk.com/files/4905142/phbk-categories.pdf)~ Replaced for a screenshot.
 I think maybe eventually navigation for the page would make sense.

**Comment by irace** [comment]
Looking great! A minor nit would be to give the category headers a bit more top padding or margin, but beyond that, this is such a huge improvement. FFT merge at your convenience

**Pull request merged**
