### PR TITLE
Design update for 2021

### LINKED ISSUE #37: Design update for 2021
Proposing a new design for the site. Willing to walk through and add details if there’s interest here.

2021 Design

### PR DESCRIPTION
**Pull request by nicbarajas**
As seen in #37 but more fleshed out in the real world. @irace, this is where I need those  👀, if you can pull the branch and take a look – but wanted to get feedback before I spend the time on updating the data wholesale.

Before | After
--- | ---
Screen Shot 2020-12-30 at 00 23 43 | Screen Shot 2020-12-30 at 00 23 50

A rundown of the changes:

- **New type, layout, etc.** It’s a little more utilitarian, so I’m happy to adjust as anyone sees fit, but also sets a clear hierarchy for places.
- **Adds blocks for hours and features.** The “Hours” and “How to Support” blocks are slightly more developed, allowing 
- **Navigation elements.** There’s a new “jump to” navigation at the top, along with “to top” arrows at the top of each (sticky) header.
- Support for addresses 

At the moment, the venues that are using the new features and hours are **333 Lounge**, **Alta Calidad** and **Fermented Grapes**. If there’s a general consensus on the new design, I’ll work on the data across all the venues for the hours.

Closes #37, #4.

### CODE REVIEW

**Comment by irace** [comment]
Hey @nicbarajas – thanks for putting this together. Onboard to help here though I’m not 100% sure when I‘ll be able to carve out the time yet, unfortunately.

**Comment by nicbarajas** [comment]
@irace fair enough! I guess if I could get a thumbs up / down on design and the new properties (hours / supports) that might be enough for me to plow ahead.

`hours` is split into sections like so:

```yaml
hours:
  - days: Sun - Thu
     hours: 11:30AM - 9:30PM
     span: 5
  - days: Fri - Sat
     hours: 11:30AM - 10PM
     span: 2
```

The `span` affects the size of the days in the frontend, so you can get a proportional-looking hours block. I don’t feel 100% about it but I was thinking more complex logic by parsing the days might be even more difficult.

`supports` is a simple list, so I think it’s more cut and dry:

```yaml
supports:
  - Outdoor Dining
  - Pickup
  - Delivery
```

If setting up the branch seems out of the cards, comment and I can drop in more screenshots as you like.

**Comment by irace** [comment]
> The `span` affects the size of the days in the frontend, so you can get a proportional-looking hours block. I don’t feel 100% about it but I was thinking more complex logic by parsing the days might be even more difficult.

Hmmm, yeah. A “better” way from an accuracy perspective would likely be for the data structure to include hours for each individual day, then have the frontend derived from that. But I could see that implementation being quite involved compared to what you have here. So while this is likely more error-prone, I think it’s more practical and have no qualms.

**Comment by irace** [comment]
This looks great! Definitely has my approval, awesome work.

**Comment by nicbarajas** [comment]
@joannaflamm Just a heads up here! This is nearly ready to go … going to give it another look-through before deploying, but might be a nice way to kick off the new year of the newsletter :)

**Pull request merged**
