### PR TITLE
Cleaner data

### PR DESCRIPTION
**Pull request by nicbarajas**
Proposing to move data for businesses into individual files. It starts down the path of the requests expressed in #4 while making individual changes less reliant on a single file.

One of the downsides of this method is the current home page is very fragile, meaning that only businesses with an explicit status show up in the listing. That said, it could help with accelerating some of the items in the wiki where an `unknown` status could be let data get scaffolded in the meantime. We should probably add something to the README or an example YML for the various data expected.

Just an idea, happy to workshop it or otherwise rethink it if this isn’t the right idea.

### CODE REVIEW

**Comment by irace** [comment]
Hmm – while part of me appreciates the increased scalability, I’m not fully sold on this approach (though am hesitant to reject it outright).

I worry about the increased friction in adding/updating places (which I tend to do fairly hastily whenever the baby happens to be napping, and this will also add friction to making edits to multiple businesses at once (or honestly, just searching for something within the file.

Will think a bit more on what exactly the problem being solved for is... 🤔

**Comment by nicbarajas** [comment]
To me, it feels a bit unwieldy to move text when the status changes from open to closed. Maybe it’s as simple as adding in the status individually.

My other thought was splitting up into places by type (e.g. cafe / coffee shop, restaurant, etc), to help with a sprawling single data file.


Totally understand if it’s not the right solution, so whatever you think is right.

**Comment by nicbarajas** [comment]
Sorry for the delay here. I’ve rethought the PR and simplified it to adding status to the places themselves. Hoping it’ll help reduce churn on the places file without becoming too complex.

**Comment by irace** [comment]
This looks great! No apologies for the delay, it’s not like I provided any concrete guidance. I like this approach a lot though.

The one change I’d suggest (if it’s not prohibitively difficult) is it might be nice if `open` is the default status, such that we assume open if not explicitly specified!

**Comment by nicbarajas** [comment]
Gonna close this and open a new PR, since this got kinda messy, but with the same info in it.

**Pull request closed without merging**
